### ISSUE TITLE
Plans for Digital Inclusion Week

### ISSUE THREAD

**Issue by danielhonker** [cityofaustin/serviceaccess#60]
If City Hall installation does not move forward.

**Comment by danielhonker** [comment]
@ADoAboutThings to share the submission link for Digital Inclusion Week proposals. Want to get people with lived experience to partner on something.

**Comment by danielhonker** [comment]
https://data.austintexas.gov/stories/s/Digital-Inclusion-Week-2019/rdt3-rvh9/

**Comment by danielhonker** [comment]
@danielhonker forward contact info for Google Fiber

**Comment by danielhonker** [comment]
@sarahscottr find a time to chat on the concept and design

**Comment by danielhonker** [comment]
AUDIENCE: 
Digital inclusion network that's already mobilized for DI week
Accessibility network that we invited to the 
Residents who face frustration with City services
Open Austin
ATA

OUTREACH:
Do512
Chronicle civic events list
Civic Futures workshop (happens the week before)

INSTALLATION/EXPERIENCE:
Move to Friday afternoon
Take pictures. Gallery of the physical spaces where the services are delivered. 
Data on the forms
Place for people to provide feedback
Forms are printed. Need to assemble them. 

**Tasks**
- [x] @danielhonker talk to John about changing to Friday -- need to work around the podcast launch? Able to use Dewitty or Austin Public Studios?
- [ ] @sarahscottr work on the installation design and build logistics
- [x] Then do outreach to secure venue
- [ ] Outreach for the event

**Comment by danielhonker** [comment]
### Date, time, location
Friday, Oct 7
Open time 1-4pm

### Design/experience

- Organize the forms by topic area
- Hang the forms 
- TV/projection to welcome people and give an overview of the project
- Offer place for people to provide feedback

### Tasks

- [ ] @sarahscottr look into materials and costs
- [ ] @sarahscottr confirm the time and details with Austin Public
- [ ] Create any slides or projection collateral
- [ ] @danielhonker review language about the event. Create an eventbrite. 
- [ ] Start promoting the event -- DIweek distro list, ATA, Austin360, etc. Emails out by COB Friday. Other outreach early next week. 
- [ ] @sarahscottr draft up postcard design. @danielhonker review and order by COB Friday.
